# Generated by Django 4.2.3 on 2023-08-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="item_image",
            field=models.ImageField(
                default="https://livingstonbagel.com/wp-content/uploads/2016/11/food-placeholder.jpg",
                max_length=500,
                upload_to="",
            ),
        ),
    ]
