# Generated by Django 4.2.3 on 2023-08-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0002_item_item_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_image",
            field=models.ImageField(
                default="https://media-cdn.tripadvisor.com/media/photo-s/1b/3d/36/a0/fresh-hand-stretched.jpg",
                max_length=500,
                upload_to="",
            ),
        ),
    ]
